name: EW_workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Eathwormproject
    - name: Run a multi-line script
      run: Endgsdym <- read.csv("Abg_SDMdyEndog.csv" )# for line trends
head(Endgsdym)
str(Endgsdym)
DFEndgDy <- data.frame(Endgsdym)
head(DFEndgDy)
    - name: Run a multi-line script
      run: |
        Endgsdym[,'Observation.date..Sampling.event.'] = as.factor(Endgsdym[,'Observation.date..Sampling.event.'])#categorical to display indiv. date
P1 <-ggplot(data = Endgsdym, aes(x =Observation.date..Sampling.event., y = Density, group=1)) + # if only one data per date
  geom_line() +
  geom_smooth(se = TRUE) +
  labs(x = "Year", y = "Abundance") 
